name: module-structure
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node 18.18.2
        uses: actions/setup-node@v1
        with:
          node-version: '18.18.2'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:ci
      - name: Archive build
